basaar_user: 'vagrant'
basaar_version: 'devel'
basaar_home: '/home/{{ basaar_user }}/basaar'
basaar_base: '/home/{{ basaar_user }}/basaar/sites/basaar/'
fixtures_variants: '{{ basaar_base }}/fixtures/variants.json'

